### ISSUE TITLE
Remove graphs from repo?

### ISSUE THREAD

**Issue by tomjaguarpaw** [awf/autodiff#11]
@zsmith3 I'm finding it awkward that the graphs are checked into the repo.  Every time I generate new graphs my working copy shows an enormous number of changes.

Am I right in presuming that these graphs were checked in so that visitors to GitHub have a convenient way of seeing them?  If so, would you mind if I remove the graphs from the repo but add them as distributed build artifacts somewhere else on the GitHub page?

**Comment by zsmith3** [comment]
> Am I right in presuming that these graphs were checked in so that visitors to GitHub have a convenient way of seeing them?

Yes.

> If so, would you mind if I remove the graphs from the repo but add them as distributed build artifacts somewhere else on the GitHub page?

Sure, that sounds like a better way of doing it.

**Comment by tomjaguarpaw** [comment]
Closed by https://github.com/awf/autodiff/commit/06ee8d1f911d019098505552887fcc8f48c08ef2
